blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/scrawl-labs/mongodb-speedwagon/discussions
    about: Open a GitHub Discussion for questions, ideas, or general feedback.
